development:
  twitter:
    key: YOUR_CONSUMER_KEY
    secret: YOUR_CONSUMER_SECRET
    options:
      site: http://twitter.com
  google:
    key: YOUR_CONSUMER_KEY
    secret: YOUR_CONSUMER_SECRET
    options:
      site: http://www.google.com


test:
  twitter:
    key: YOUR_CONSUMER_KEY
    secret: YOUR_CONSUMER_SECRET
    options:
      site: http://twitter.com
  google:
    key: YOUR_CONSUMER_KEY
    secret: YOUR_CONSUMER_SECRET
    options:
      site: http://www.google.com

